### ISSUE TITLE
Can't seem to change the season dates

### ISSUE THREAD

**Issue by DoctorWaffles** [stoopkid1/ezleague#127]
All my season dates seem to be static and everytime I try to change them (backend) they keep changing back to January 01, 1970.

**Comment by zigstum** [comment]
The create season button is forthcoming..
Find the file ezl_install_folder/admin/tpls/leagues/season-create.php
At line 33 insert this:
<a href="leagues.php?page=create_season&id=<?php echo $league['id']; ?>" class="btn btn-success btn-xs">Create Season</a>
If you don't want to change code, you could navigate to the address above in your browser, and add the league id to the query yourself (?page=create_season&id=) yourself.

**Comment by stoopkid1** [comment]
@DoctorWaffles @zigstum 
creating a new season & modifying a seasons start/end/registration dates is already implemented:

Create new season:
![screenshot 2015-04-04 21 37 20](https://cloud.githubusercontent.com/assets/2205744/6995519/1a4884a8-db13-11e4-906d-2d900f35364a.png)

From the View All Leagues page, click on the League that you want to edit, or modify the season information:
![screenshot 2015-04-04 21 40 08](https://cloud.githubusercontent.com/assets/2205744/6995520/38bb8b92-db13-11e4-8ccf-33eef43c5cff.png)

**Comment by stevej891** [comment]
im having issues with this my season dates are staying at december 31 1969 ive tried updating this  3 times

**Comment by stoopkid1** [comment]
@stevej891 few questions to help me diagnose the bug... 
have you set the Timezone setting in your admin panel? 
have you made any News posts that are also showing the incorrect dates?
what timezone are you in?
do you know where your web server is located?

![screenshot 2015-04-09 01 07 16](https://cloud.githubusercontent.com/assets/2205744/7061258/d1129b80-de54-11e4-985b-a8c79129a65e.png)

**Comment by bigbambu** [comment]
Hello!

On my server that is a VPS i found the following errors.
mod_fcgid: stderr: PHP Warning:  date(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected 'America/New_York' for 'EDT/-4.0/DST' instead in /var/www/clients/client0/web2/web/lol/lib/objects/class-team.php on line 382, referer: http://mydomain.com/lol/settings-guild.php?page=match&view=details&mid=1

-And another error is 

mod_fcgid: stderr: PHP Fatal error:  Uncaught exception 'Exception' with message 'DateTime::__construct(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected 'America/New_York' for 'EDT/-4.0/DST' instead' in /var/www/clients/client0/web2/web/lol/lib/class-frontend.php:433, referer: http://mydomain.com/lol/settings-guild.php?page=leagues&id=1&view=schedule

mod_fcgid: stderr: PHP Warning:  strtotime(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected 'America/New_York' for 'EDT/-4.0/DST' instead in /var/www/clients/client0/web2/web/lol/view-league.php on line 124, referer: http://rrjeti.al/lol/view-team.php?id=2

and so on.

Regards

**Comment by stoopkid1** [comment]
@bigbambu have you set the timezone in your Admin Panel's Site Settings?
since you have a VPS, you can also try modifying your php.ini file, and adding: 
`date.timezone = America/Chicago` be sure to restart your web server after modifying php.ini

**Comment by stoopkid1** [comment]
a possible fix has been pushed and merged into ezLeague (v3.4.9 https://github.com/stoopkid1/ezleague/pull/149). please let me know if this resolves your issue

**Comment by stevej891** [comment]
this still did not fix the issue i have reset it back too 3.4.9 still does
not work when i try to update although when i do that it set the date to
january 1 1970 instead of december 31 1969  lol dont know y

**Comment by stevej891** [comment]
http://gyazo.com/cae3272064a8b1897b60a2335735147a

**Comment by stoopkid1** [comment]
@stevej891 would you be able to give me FTP access to your ezLeague install? i'd like to do some debugging since i can't replicate your date issue locally, or on my VPS.

my email is MDLoring[at]gmail.com

**Comment by stevej891** [comment]
sure


playercompete.com
esports
fishing91

**Comment by stevej891** [comment]
its under playercompete.com/league

**Comment by stoopkid1** [comment]
@stevej891 thanks steve. i'll take a look shortly and let you know. i've deleted your previous post so its not public

**Comment by zigstum** [comment]
It's still on the mail-list.
Maybe better to change pwd and resend in PM.

**Comment by stoopkid1** [comment]
@zigstum yes absolutely. thanks zigstum.
@stevej891 please reset the password and PM me it, or email me it MDLoring[at]gmail.com

**Comment by stevej891** [comment]
ok thanks

**Comment by stevej891** [comment]
i went ahead and emailed it to you Thanks

**Comment by stoopkid1** [comment]
issue resolved https://github.com/stoopkid1/ezleague/pull/152
